language: python
python:
  - "3.8"
cache:
  directories:
    - $HOME/verilator
before_install:
  - sudo apt-get update
  - sudo apt-get -y install git make autoconf g++
  - if [ ! -d $HOME/verilator ]; then cd $HOME && git clone https://github.com/verilator/verilator.git; fi
  - cd $HOME/verilator && if [ "$(git pull)" != "Already up to date." ]; then autoconf && ./configure && make -j2 && sudo make install; fi && cd ..
install:
  - pip install -r requirements.txt
script:
  - python testing/bp_test.py