language: python
python:
  - "3.8"
before_install:
  - sudo apt-get update
  - sudo apt-get -y install git make autoconf g++
  - if [ ! -d verilator ]; then git clone https://github.com/verilator/verilator.git; fi
  - cd verilator && if [ "$(git pull)" != "Already up to date." ] || [ ! -f bin/verilator ]; then autoconf && ./configure && make -j2 && sudo make install; fi && cd ..
install:
  - pip install -r requirements.txt
script:
  - python testing/bp_test.py